import { Injectable } from '@angular/core';

export interface Event {
  id: number;
  title: string;
  description: string;
  longDescription: string;
  date: string;
  isoDate: string;
  day: string;
  month: string;
  time: string;
  endTime: string;
  location: string;
  locationDetail: string;
  discipline: string;
  category: string;
  image: string;
  schedule: { time: string; activity: string }[];
  categories: string[];
  inscription: {
    open: boolean;
    deadline: string;
    contact: string;
  };
  rules: string[];
  prizes: string[];
}

@Injectable({ providedIn: 'root' })
export class EventsService {
  private events: Event[] = [
    {
      id: 15,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '2 Sep 2026',
      isoDate: '2026-09-02',
      day: '02',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 16,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '5 Sep 2026',
      isoDate: '2026-09-05',
      day: '05',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 17,
      title: 'Torneo de Truco Inter-Socios',
      description: 'Torneo relámpago de truco en la confitería del club.',
      longDescription: 'Demuestra quién tiene más picardía en las cartas. Torneo de truco en parejas organizado en la confitería del club, con consumiciones incluidas en la inscripción.',
      date: '9 Sep 2026',
      isoDate: '2026-09-09',
      day: '09',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '00:00 hs',
      location: 'Confitería del Club',
      locationDetail: 'Planta baja.',
      discipline: 'Recreación',
      category: 'Sociales',
      image: 'images/pool.png',
      schedule: [{"time":"19:00","activity":"Sorteo de mesas"},{"time":"19:15","activity":"Fase de grupos"}],
      categories: ["Parejas libres"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"bufet@avellanedafc.com"},
      rules: ["Prohibido el uso de señas de la vieja guardia (solo señas oficiales)"],
      prizes: ["Cena gratis para los campeones","Trofeo"]
    },
    {
      id: 18,
      title: 'Jornada Solidaria: Colecta de Alimentos',
      description: 'Día de donación de alimentos no perecederos para comedores locales.',
      longDescription: 'Avellaneda FC se une a la comunidad en esta gran jornada solidaria. Todo lo recolectado será donado a tres comedores infantiles de la zona. Se realizarán sorteos entre los donantes.',
      date: '12 Sep 2026',
      isoDate: '2026-09-12',
      day: '12',
      month: 'SEP',
      time: '10:00 hs',
      endTime: '18:00 hs',
      location: 'Acceso Principal',
      locationDetail: 'Mesa de recepción en el lobby.',
      discipline: 'Social',
      category: 'Institucionales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"10:00","activity":"Inicio de recepción de donaciones"},{"time":"17:30","activity":"Sorteo de premios"}],
      categories: ["Público en general"],
      inscription: {"open":false,"deadline":"N/A","contact":"solidaridad@avellanedafc.com"},
      rules: ["Se aceptan fideos, arroz, leche en polvo y conservas"],
      prizes: ["Camiseta oficial autografiada"]
    },
    {
      id: 19,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '16 Sep 2026',
      isoDate: '2026-09-16',
      day: '16',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 10,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '19 Sep 2026',
      isoDate: '2026-09-19',
      day: '19',
      month: 'SEP',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 20,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '23 Sep 2026',
      isoDate: '2026-09-23',
      day: '23',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 21,
      title: 'Torneo de Truco Inter-Socios',
      description: 'Torneo relámpago de truco en la confitería del club.',
      longDescription: 'Demuestra quién tiene más picardía en las cartas. Torneo de truco en parejas organizado en la confitería del club, con consumiciones incluidas en la inscripción.',
      date: '26 Sep 2026',
      isoDate: '2026-09-26',
      day: '26',
      month: 'SEP',
      time: '19:00 hs',
      endTime: '00:00 hs',
      location: 'Confitería del Club',
      locationDetail: 'Planta baja.',
      discipline: 'Recreación',
      category: 'Sociales',
      image: 'images/pool.png',
      schedule: [{"time":"19:00","activity":"Sorteo de mesas"},{"time":"19:15","activity":"Fase de grupos"}],
      categories: ["Parejas libres"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"bufet@avellanedafc.com"},
      rules: ["Prohibido el uso de señas de la vieja guardia (solo señas oficiales)"],
      prizes: ["Cena gratis para los campeones","Trofeo"]
    },
    {
      id: 1,
      title: 'Torneo Interclubes de Fútbol',
      description: 'Gran torneo regional con la participación de más de 20 clubes de la zona. Categorías Sub-15, Sub-17 y Primera División.',
      longDescription: 'El Torneo Interclubes de Fútbol es uno de los eventos deportivos más importantes del calendario de Avellaneda FC. Con más de dos décadas de historia, este torneo reúne a los mejores clubes de la región en una competencia de alto nivel que combina deporte, amistad y compañerismo.',
      date: '27 Sep 2026',
      isoDate: '2026-09-27',
      day: '27',
      month: 'SEP',
      time: '09:00 hs',
      endTime: '19:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Av. Mitre 1200, Avellaneda. Acceso por portón principal.',
      discipline: 'Fútbol',
      category: 'Torneos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"08:00","activity":"Acreditación de equipos"},{"time":"09:00","activity":"Inicio de partidos"}],
      categories: ["Sub-15","Sub-17","Primera División"],
      inscription: {"open":true,"deadline":"24 Sep 2026","contact":"secretaria@avellanedafc.com"},
      rules: ["Mínimo 11 jugadores"],
      prizes: ["🥇 1° Puesto: Trofeo + Medallas"]
    },
    {
      id: 22,
      title: 'Encuentro de Mini-Vóley',
      description: 'Jornada recreativa con clubes invitados para categorías infantiles.',
      longDescription: 'Gran encuentro de Mini-Vóley recibiendo a más de 5 clubes amigos de la ciudad. El objetivo es fomentar el deporte, el compañerismo y el juego en equipo en las categorías formativas.',
      date: '3 Oct 2026',
      isoDate: '2026-10-03',
      day: '03',
      month: 'OCT',
      time: '10:00 hs',
      endTime: '15:00 hs',
      location: 'Polideportivo Auxiliar',
      locationDetail: 'Canchas 2 y 3.',
      discipline: 'Vóley',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"10:00","activity":"Recepción de delegaciones"},{"time":"10:30","activity":"Inicio de rotaciones"}],
      categories: ["Sub-10","Sub-12"],
      inscription: {"open":false,"deadline":"N/A","contact":"voley@avellanedafc.com"},
      rules: ["Juego limpio y respeto obligatorio","No se computan puntos oficiales"],
      prizes: ["Diploma de asistencia"]
    },
    {
      id: 2,
      title: 'Campeonato de Tenis 2026',
      description: 'Torneo interno anual de tenis con categorías singles y dobles.',
      longDescription: 'El Campeonato de Tenis 2026 de Avellaneda FC es el evento más esperado por los tenistas del club. Este torneo interno reúne a jugadores de todos los niveles en un formato round-robin.',
      date: '4 Oct 2026',
      isoDate: '2026-10-04',
      day: '04',
      month: 'OCT',
      time: '10:00 hs',
      endTime: '20:00 hs',
      location: 'Canchas de Tenis — Avellaneda FC',
      locationDetail: 'Complejo de tenis, sector norte del predio.',
      discipline: 'Tenis',
      category: 'Deportivos',
      image: 'images/tennis.png',
      schedule: [{"time":"09:30","activity":"Acreditación"}],
      categories: ["Singles Masculino A","Singles Femenino","Dobles"],
      inscription: {"open":false,"deadline":"1 Oct 2026","contact":"tenis@avellanedafc.com"},
      rules: ["Sets al mejor de 3"],
      prizes: ["🥇 Campeón: Trofeo"]
    },
    {
      id: 23,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '10 Oct 2026',
      isoDate: '2026-10-10',
      day: '10',
      month: 'OCT',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 24,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '14 Oct 2026',
      isoDate: '2026-10-14',
      day: '14',
      month: 'OCT',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 25,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '17 Oct 2026',
      isoDate: '2026-10-17',
      day: '17',
      month: 'OCT',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    },
    {
      id: 3,
      title: 'Liga Regional de Básquet - Final',
      description: 'La gran final de la liga regional donde Avellaneda FC buscará el campeonato.',
      longDescription: 'La Final de la Liga Regional de Básquet es el partido más importante del año para la sección de básquet de Avellaneda FC.',
      date: '18 Oct 2026',
      isoDate: '2026-10-18',
      day: '18',
      month: 'OCT',
      time: '20:00 hs',
      endTime: '22:30 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Sector polideportivo, ingreso por Av. Mitre 1200.',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"20:00","activity":"Salto inicial"}],
      categories: ["Primera División Masculina"],
      inscription: {"open":false,"deadline":"N/A","contact":"secretaria@avellanedafc.com"},
      rules: ["Puntualidad"],
      prizes: ["🏆 Campeón: Trofeo"]
    },
    {
      id: 11,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '24 Oct 2026',
      isoDate: '2026-10-24',
      day: '24',
      month: 'OCT',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 26,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '28 Oct 2026',
      isoDate: '2026-10-28',
      day: '28',
      month: 'OCT',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 27,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '31 Oct 2026',
      isoDate: '2026-10-31',
      day: '31',
      month: 'OCT',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 28,
      title: 'Clínica Especial de Tenis con ex-profesionales',
      description: 'Día de entrenamiento técnico avanzado dictado por invitados especiales.',
      longDescription: 'Una oportunidad única para socios del club. Clínicas prácticas de derecha, revés y saque, a cargo de figuras reconocidas del tenis nacional e internacional.',
      date: '4 Nov 2026',
      isoDate: '2026-11-04',
      day: '04',
      month: 'NOV',
      time: '14:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Tenis',
      locationDetail: 'Canchas 1 a 4 (Polvo de ladrillo).',
      discipline: 'Tenis',
      category: 'Deportivos',
      image: 'images/tennis.png',
      schedule: [{"time":"14:00","activity":"Clínica de saques"},{"time":"16:00","activity":"Estrategia de dobles"}],
      categories: ["Mayores de 15 años","Nivel Intermedio/Avanzado"],
      inscription: {"open":true,"deadline":"3 días antes","contact":"tenis@avellanedafc.com"},
      rules: ["Cupos limitados (20 personas por cancha)"],
      prizes: ["Sorteos de indumentaria"]
    },
    {
      id: 29,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '7 Nov 2026',
      isoDate: '2026-11-07',
      day: '07',
      month: 'NOV',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    },
    {
      id: 30,
      title: 'Jornada Solidaria: Colecta de Alimentos',
      description: 'Día de donación de alimentos no perecederos para comedores locales.',
      longDescription: 'Avellaneda FC se une a la comunidad en esta gran jornada solidaria. Todo lo recolectado será donado a tres comedores infantiles de la zona. Se realizarán sorteos entre los donantes.',
      date: '11 Nov 2026',
      isoDate: '2026-11-11',
      day: '11',
      month: 'NOV',
      time: '10:00 hs',
      endTime: '18:00 hs',
      location: 'Acceso Principal',
      locationDetail: 'Mesa de recepción en el lobby.',
      discipline: 'Social',
      category: 'Institucionales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"10:00","activity":"Inicio de recepción de donaciones"},{"time":"17:30","activity":"Sorteo de premios"}],
      categories: ["Público en general"],
      inscription: {"open":false,"deadline":"N/A","contact":"solidaridad@avellanedafc.com"},
      rules: ["Se aceptan fideos, arroz, leche en polvo y conservas"],
      prizes: ["Camiseta oficial autografiada"]
    },
    {
      id: 31,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '14 Nov 2026',
      isoDate: '2026-11-14',
      day: '14',
      month: 'NOV',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 32,
      title: 'Encuentro de Mini-Vóley',
      description: 'Jornada recreativa con clubes invitados para categorías infantiles.',
      longDescription: 'Gran encuentro de Mini-Vóley recibiendo a más de 5 clubes amigos de la ciudad. El objetivo es fomentar el deporte, el compañerismo y el juego en equipo en las categorías formativas.',
      date: '18 Nov 2026',
      isoDate: '2026-11-18',
      day: '18',
      month: 'NOV',
      time: '10:00 hs',
      endTime: '15:00 hs',
      location: 'Polideportivo Auxiliar',
      locationDetail: 'Canchas 2 y 3.',
      discipline: 'Vóley',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"10:00","activity":"Recepción de delegaciones"},{"time":"10:30","activity":"Inicio de rotaciones"}],
      categories: ["Sub-10","Sub-12"],
      inscription: {"open":false,"deadline":"N/A","contact":"voley@avellanedafc.com"},
      rules: ["Juego limpio y respeto obligatorio","No se computan puntos oficiales"],
      prizes: ["Diploma de asistencia"]
    },
    {
      id: 12,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '21 Nov 2026',
      isoDate: '2026-11-21',
      day: '21',
      month: 'NOV',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 33,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '25 Nov 2026',
      isoDate: '2026-11-25',
      day: '25',
      month: 'NOV',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 34,
      title: 'Torneo de Truco Inter-Socios',
      description: 'Torneo relámpago de truco en la confitería del club.',
      longDescription: 'Demuestra quién tiene más picardía en las cartas. Torneo de truco en parejas organizado en la confitería del club, con consumiciones incluidas en la inscripción.',
      date: '28 Nov 2026',
      isoDate: '2026-11-28',
      day: '28',
      month: 'NOV',
      time: '19:00 hs',
      endTime: '00:00 hs',
      location: 'Confitería del Club',
      locationDetail: 'Planta baja.',
      discipline: 'Recreación',
      category: 'Sociales',
      image: 'images/pool.png',
      schedule: [{"time":"19:00","activity":"Sorteo de mesas"},{"time":"19:15","activity":"Fase de grupos"}],
      categories: ["Parejas libres"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"bufet@avellanedafc.com"},
      rules: ["Prohibido el uso de señas de la vieja guardia (solo señas oficiales)"],
      prizes: ["Cena gratis para los campeones","Trofeo"]
    },
    {
      id: 4,
      title: 'Cena Anual del Club',
      description: 'Celebramos otro año de crecimiento con nuestra cena anual.',
      longDescription: 'La Cena Anual de Avellaneda FC es la celebración más importante de la vida social del club.',
      date: '29 Nov 2026',
      isoDate: '2026-11-29',
      day: '29',
      month: 'NOV',
      time: '21:00 hs',
      endTime: '02:00 hs',
      location: 'Salón de Eventos',
      locationDetail: 'Salón principal del club.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:00","activity":"Recepción"}],
      categories: ["Socios activos","Invitados"],
      inscription: {"open":true,"deadline":"15 Nov 2026","contact":"eventos@avellanedafc.com"},
      rules: ["Dress code: formal"],
      prizes: ["🏅 Mejor Atleta del Año"]
    },
    {
      id: 35,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '5 Dic 2026',
      isoDate: '2026-12-05',
      day: '05',
      month: 'DIC',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 36,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '9 Dic 2026',
      isoDate: '2026-12-09',
      day: '09',
      month: 'DIC',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    },
    {
      id: 37,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '12 Dic 2026',
      isoDate: '2026-12-12',
      day: '12',
      month: 'DIC',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 38,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '16 Dic 2026',
      isoDate: '2026-12-16',
      day: '16',
      month: 'DIC',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 5,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '19 Dic 2026',
      isoDate: '2026-12-19',
      day: '19',
      month: 'DIC',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 39,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '23 Dic 2026',
      isoDate: '2026-12-23',
      day: '23',
      month: 'DIC',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 40,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '26 Dic 2026',
      isoDate: '2026-12-26',
      day: '26',
      month: 'DIC',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 41,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '30 Dic 2026',
      isoDate: '2026-12-30',
      day: '30',
      month: 'DIC',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 42,
      title: 'Clínica Especial de Tenis con ex-profesionales',
      description: 'Día de entrenamiento técnico avanzado dictado por invitados especiales.',
      longDescription: 'Una oportunidad única para socios del club. Clínicas prácticas de derecha, revés y saque, a cargo de figuras reconocidas del tenis nacional e internacional.',
      date: '2 Ene 2027',
      isoDate: '2027-01-02',
      day: '02',
      month: 'ENE',
      time: '14:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Tenis',
      locationDetail: 'Canchas 1 a 4 (Polvo de ladrillo).',
      discipline: 'Tenis',
      category: 'Deportivos',
      image: 'images/tennis.png',
      schedule: [{"time":"14:00","activity":"Clínica de saques"},{"time":"16:00","activity":"Estrategia de dobles"}],
      categories: ["Mayores de 15 años","Nivel Intermedio/Avanzado"],
      inscription: {"open":true,"deadline":"3 días antes","contact":"tenis@avellanedafc.com"},
      rules: ["Cupos limitados (20 personas por cancha)"],
      prizes: ["Sorteos de indumentaria"]
    },
    {
      id: 6,
      title: 'Inicio Colonia de Vacaciones',
      description: 'Arranca la temporada de verano 2027 para los más chicos.',
      longDescription: 'Nuestra tradicional Colonia de Vacaciones abre sus puertas para recibir a cientos de chicos que disfrutarán de actividades recreativas, pileta y deportes.',
      date: '4 Ene 2027',
      isoDate: '2027-01-04',
      day: '04',
      month: 'ENE',
      time: '08:30 hs',
      endTime: '12:30 hs',
      location: 'Sector Pileta y Quinchos',
      locationDetail: 'Ingreso exclusivo por entrada secundaria.',
      discipline: 'Recreación',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"08:30","activity":"Recepción de colonos"}],
      categories: ["Infantiles (4 a 12 años)"],
      inscription: {"open":true,"deadline":"20 Dic 2026","contact":"colonia@avellanedafc.com"},
      rules: ["Certificado médico obligatorio"],
      prizes: []
    },
    {
      id: 43,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '9 Ene 2027',
      isoDate: '2027-01-09',
      day: '09',
      month: 'ENE',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 44,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '13 Ene 2027',
      isoDate: '2027-01-13',
      day: '13',
      month: 'ENE',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 45,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '16 Ene 2027',
      isoDate: '2027-01-16',
      day: '16',
      month: 'ENE',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 46,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '20 Ene 2027',
      isoDate: '2027-01-20',
      day: '20',
      month: 'ENE',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 7,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '23 Ene 2027',
      isoDate: '2027-01-23',
      day: '23',
      month: 'ENE',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 47,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '27 Ene 2027',
      isoDate: '2027-01-27',
      day: '27',
      month: 'ENE',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 48,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '30 Ene 2027',
      isoDate: '2027-01-30',
      day: '30',
      month: 'ENE',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    },
    {
      id: 49,
      title: 'Clínica Especial de Tenis con ex-profesionales',
      description: 'Día de entrenamiento técnico avanzado dictado por invitados especiales.',
      longDescription: 'Una oportunidad única para socios del club. Clínicas prácticas de derecha, revés y saque, a cargo de figuras reconocidas del tenis nacional e internacional.',
      date: '3 Feb 2027',
      isoDate: '2027-02-03',
      day: '03',
      month: 'FEB',
      time: '14:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Tenis',
      locationDetail: 'Canchas 1 a 4 (Polvo de ladrillo).',
      discipline: 'Tenis',
      category: 'Deportivos',
      image: 'images/tennis.png',
      schedule: [{"time":"14:00","activity":"Clínica de saques"},{"time":"16:00","activity":"Estrategia de dobles"}],
      categories: ["Mayores de 15 años","Nivel Intermedio/Avanzado"],
      inscription: {"open":true,"deadline":"3 días antes","contact":"tenis@avellanedafc.com"},
      rules: ["Cupos limitados (20 personas por cancha)"],
      prizes: ["Sorteos de indumentaria"]
    },
    {
      id: 50,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '6 Feb 2027',
      isoDate: '2027-02-06',
      day: '06',
      month: 'FEB',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 51,
      title: 'Clínica Especial de Tenis con ex-profesionales',
      description: 'Día de entrenamiento técnico avanzado dictado por invitados especiales.',
      longDescription: 'Una oportunidad única para socios del club. Clínicas prácticas de derecha, revés y saque, a cargo de figuras reconocidas del tenis nacional e internacional.',
      date: '10 Feb 2027',
      isoDate: '2027-02-10',
      day: '10',
      month: 'FEB',
      time: '14:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Tenis',
      locationDetail: 'Canchas 1 a 4 (Polvo de ladrillo).',
      discipline: 'Tenis',
      category: 'Deportivos',
      image: 'images/tennis.png',
      schedule: [{"time":"14:00","activity":"Clínica de saques"},{"time":"16:00","activity":"Estrategia de dobles"}],
      categories: ["Mayores de 15 años","Nivel Intermedio/Avanzado"],
      inscription: {"open":true,"deadline":"3 días antes","contact":"tenis@avellanedafc.com"},
      rules: ["Cupos limitados (20 personas por cancha)"],
      prizes: ["Sorteos de indumentaria"]
    },
    {
      id: 52,
      title: 'Torneo de Truco Inter-Socios',
      description: 'Torneo relámpago de truco en la confitería del club.',
      longDescription: 'Demuestra quién tiene más picardía en las cartas. Torneo de truco en parejas organizado en la confitería del club, con consumiciones incluidas en la inscripción.',
      date: '13 Feb 2027',
      isoDate: '2027-02-13',
      day: '13',
      month: 'FEB',
      time: '19:00 hs',
      endTime: '00:00 hs',
      location: 'Confitería del Club',
      locationDetail: 'Planta baja.',
      discipline: 'Recreación',
      category: 'Sociales',
      image: 'images/pool.png',
      schedule: [{"time":"19:00","activity":"Sorteo de mesas"},{"time":"19:15","activity":"Fase de grupos"}],
      categories: ["Parejas libres"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"bufet@avellanedafc.com"},
      rules: ["Prohibido el uso de señas de la vieja guardia (solo señas oficiales)"],
      prizes: ["Cena gratis para los campeones","Trofeo"]
    },
    {
      id: 8,
      title: 'Triatlón Anual Avellaneda',
      description: 'Competencia combinada de natación, ciclismo (virtual) y running.',
      longDescription: 'Pon a prueba tu resistencia en nuestro Triatlón de Verano. Pileta olímpica, bicicletas estáticas y circuito de running en la pista de atletismo.',
      date: '14 Feb 2027',
      isoDate: '2027-02-14',
      day: '14',
      month: 'FEB',
      time: '07:30 hs',
      endTime: '13:00 hs',
      location: 'Complejo Deportivo',
      locationDetail: 'Circuito integral interno.',
      discipline: 'Atletismo',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"07:30","activity":"Largada Natación"}],
      categories: ["General Femenino","General Masculino"],
      inscription: {"open":true,"deadline":"10 Feb 2027","contact":"deportes@avellanedafc.com"},
      rules: ["Apto físico obligatorio"],
      prizes: ["Medalla finisher para todos"]
    },
    {
      id: 13,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '20 Feb 2027',
      isoDate: '2027-02-20',
      day: '20',
      month: 'FEB',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 53,
      title: 'Encuentro de Mini-Vóley',
      description: 'Jornada recreativa con clubes invitados para categorías infantiles.',
      longDescription: 'Gran encuentro de Mini-Vóley recibiendo a más de 5 clubes amigos de la ciudad. El objetivo es fomentar el deporte, el compañerismo y el juego en equipo en las categorías formativas.',
      date: '24 Feb 2027',
      isoDate: '2027-02-24',
      day: '24',
      month: 'FEB',
      time: '10:00 hs',
      endTime: '15:00 hs',
      location: 'Polideportivo Auxiliar',
      locationDetail: 'Canchas 2 y 3.',
      discipline: 'Vóley',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"10:00","activity":"Recepción de delegaciones"},{"time":"10:30","activity":"Inicio de rotaciones"}],
      categories: ["Sub-10","Sub-12"],
      inscription: {"open":false,"deadline":"N/A","contact":"voley@avellanedafc.com"},
      rules: ["Juego limpio y respeto obligatorio","No se computan puntos oficiales"],
      prizes: ["Diploma de asistencia"]
    },
    {
      id: 54,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '27 Feb 2027',
      isoDate: '2027-02-27',
      day: '27',
      month: 'FEB',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 55,
      title: 'Reunión de Comisión Directiva Abierta',
      description: 'Sesión informativa mensual sobre avances de obras y finanzas.',
      longDescription: 'Se convoca a todos los socios activos a la reunión informativa mensual de la Comisión Directiva. Se presentarán los balances financieros del mes y el estado de avance de las nuevas obras de infraestructura del club.',
      date: '3 Mar 2027',
      isoDate: '2027-03-03',
      day: '03',
      month: 'MAR',
      time: '20:00 hs',
      endTime: '22:00 hs',
      location: 'Salón de Actos',
      locationDetail: 'Primer piso de la Sede Social.',
      discipline: 'Administración',
      category: 'Institucionales',
      image: 'images/pool.png',
      schedule: [{"time":"20:00","activity":"Apertura de sesión"},{"time":"20:15","activity":"Informe financiero"}],
      categories: ["Socios Plenos"],
      inscription: {"open":true,"deadline":"1 día antes","contact":"comision@avellanedafc.com"},
      rules: ["Carnet de socio al día obligatorio para ingresar"],
      prizes: []
    },
    {
      id: 56,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '6 Mar 2027',
      isoDate: '2027-03-06',
      day: '06',
      month: 'MAR',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 9,
      title: 'Inicio de Temporada Oficial 2027',
      description: 'Presentación de equipos federados y apertura del año deportivo.',
      longDescription: 'Gran evento de presentación de planteles de Primera, inauguración de nuevas instalaciones y desfile de delegaciones.',
      date: '7 Mar 2027',
      isoDate: '2027-03-07',
      day: '07',
      month: 'MAR',
      time: '18:00 hs',
      endTime: '22:00 hs',
      location: 'Cancha Principal de Fútbol',
      locationDetail: 'Tribuna central habilitada.',
      discipline: 'Multideporte',
      category: 'Institucionales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"18:30","activity":"Desfile inaugural"}],
      categories: ["Todas las disciplinas"],
      inscription: {"open":false,"deadline":"N/A","contact":"secretaria@avellanedafc.com"},
      rules: ["Vestimenta del club obligatoria para atletas"],
      prizes: []
    },
    {
      id: 57,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '13 Mar 2027',
      isoDate: '2027-03-13',
      day: '13',
      month: 'MAR',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 58,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '17 Mar 2027',
      isoDate: '2027-03-17',
      day: '17',
      month: 'MAR',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    },
    {
      id: 14,
      title: 'Peña Folklórica del Club',
      description: 'Noche de tradición, empanadas, vino y shows en vivo.',
      longDescription: 'Acercate con tu familia a disfrutar de una verdadera peña folklórica en el quincho del club. Habrá buffet a cargo de la subcomisión de eventos y grupos de baile folklórico invitados.',
      date: '20 Mar 2027',
      isoDate: '2027-03-20',
      day: '20',
      month: 'MAR',
      time: '21:30 hs',
      endTime: '02:00 hs',
      location: 'Quincho Principal',
      locationDetail: 'Sector parrillas.',
      discipline: 'Social',
      category: 'Sociales',
      image: 'images/football_pitch.png',
      schedule: [{"time":"21:30","activity":"Apertura de parrilla"},{"time":"23:00","activity":"Shows en vivo"}],
      categories: ["Abierto a todo público"],
      inscription: {"open":true,"deadline":"Venta en puerta","contact":"eventos@avellanedafc.com"},
      rules: ["Ambiente familiar"],
      prizes: []
    },
    {
      id: 59,
      title: 'Torneo Interno de Natación',
      description: 'Competencia mensual para alumnos de la escuela de natación.',
      longDescription: 'Torneo formativo y amistoso destinado a que los alumnos de nuestra escuela de natación pongan a prueba sus avances mensuales en un entorno competitivo pero amigable.',
      date: '24 Mar 2027',
      isoDate: '2027-03-24',
      day: '24',
      month: 'MAR',
      time: '09:00 hs',
      endTime: '13:00 hs',
      location: 'Piscina Olímpica',
      locationDetail: 'Acceso por vestuarios.',
      discipline: 'Natación',
      category: 'Torneos',
      image: 'images/pool.png',
      schedule: [{"time":"09:00","activity":"Ablande"},{"time":"09:45","activity":"Series 50m Libres"}],
      categories: ["Pre-Equipo","Escuela de Natación"],
      inscription: {"open":true,"deadline":"Mismo día","contact":"natacion@avellanedafc.com"},
      rules: ["Uso de gorra oficial del club"],
      prizes: ["Medallas de participación para todos"]
    },
    {
      id: 60,
      title: 'Jornada de Entrenamiento Abierto de Básquet',
      description: 'Entrenamiento a puertas abiertas para visualizar nuevas tácticas.',
      longDescription: 'Ven a presenciar el entrenamiento del plantel superior de Básquet de Avellaneda FC. Una jornada especial donde el cuerpo técnico abrirá las puertas para que los socios conozcan las nuevas metodologías de trabajo táctico.',
      date: '27 Mar 2027',
      isoDate: '2027-03-27',
      day: '27',
      month: 'MAR',
      time: '19:00 hs',
      endTime: '21:00 hs',
      location: 'Polideportivo Cubierto',
      locationDetail: 'Ingreso exclusivo socios por Av. Mitre',
      discipline: 'Básquet',
      category: 'Deportivos',
      image: 'images/gym.png',
      schedule: [{"time":"19:00","activity":"Calentamiento"},{"time":"19:30","activity":"Práctica formal"}],
      categories: ["Público general socio"],
      inscription: {"open":false,"deadline":"N/A","contact":"basquet@avellanedafc.com"},
      rules: ["Prohibido filmar la práctica táctica","Hacer silencio durante las explicaciones del DT"],
      prizes: []
    },
    {
      id: 61,
      title: 'Amistoso de Fútbol Femenino vs Club Atlético Mitre',
      description: 'Partido preparatorio de pretemporada para la Primera División Femenina.',
      longDescription: 'Nuestras chicas de Primera División disputan un amistoso de alto voltaje frente al Club Atlético Mitre como parte de la puesta a punto para la temporada oficial.',
      date: '31 Mar 2027',
      isoDate: '2027-03-31',
      day: '31',
      month: 'MAR',
      time: '16:00 hs',
      endTime: '18:00 hs',
      location: 'Canchas de Fútbol - Sede Principal',
      locationDetail: 'Entrada por tribuna local.',
      discipline: 'Fútbol',
      category: 'Deportivos',
      image: 'images/football_pitch.png',
      schedule: [{"time":"16:00","activity":"Silbatazo inicial"},{"time":"16:45","activity":"Entretiempo"}],
      categories: ["Primera División Femenina"],
      inscription: {"open":false,"deadline":"N/A","contact":"futbol.fem@avellanedafc.com"},
      rules: ["No se permite el ingreso con bebidas alcohólicas"],
      prizes: []
    }
  ];

  getAll(): Event[] { return this.events; }
  getById(id: number): Event | undefined { return this.events.find(e => e.id === id); }
  getUpcoming(n?: number): Event[] { 
    const sorted = [...this.events].sort((a,b) => new Date(a.isoDate).getTime() - new Date(b.isoDate).getTime());
    return n ? sorted.slice(0, n) : sorted; 
  }
  getByCategory(cat: string): Event[] {
    if (cat === 'Todos') return this.events;
    return this.events.filter(e => e.category === cat);
  }
  getCategories(): string[] { return ['Todos los eventos', 'Deportivos', 'Torneos', 'Sociales', 'Institucionales']; }
}
